branches:
  only:
    - staging
    - master
    - trying

language: rust

matrix:
  include:
  - name: "miri"
    script:
    - rm -rf ./target
    - ./run-miri-tests.sh

  - rust: stable
    script:
    - cargo test
    - cargo test --release

  - rust: beta
    script:
    - cargo test
    - cargo test --release

  - rust: stable
    script:
    - cargo test --no-default-features --features "std parking_lot"
    - cargo test --no-default-features --features "std parking_lot" --release

  - rust: stable
    script:
    - cargo build --no-default-features --test test

  - rust: 1.31.1
    script:
    - mv Cargo.lock.min Cargo.lock
    - cargo build
